# Generated by Django 2.2.2 on 2020-02-12 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
