# Generated by Django 2.2.2 on 2020-02-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, verbose_name='제품종류')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('damage', models.CharField(max_length=100, verbose_name='파손부위')),
            ],
        ),
    ]
