# Generated by Django 2.2.2 on 2020-02-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0006_delete_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyeong', models.IntegerField(verbose_name='평형')),
                ('product_type', models.CharField(max_length=100, verbose_name='종류')),
                ('p_type', models.CharField(max_length=100, verbose_name='소종류')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('price', models.IntegerField(verbose_name='가격')),
            ],
        ),
    ]
