# Generated by Django 2.2.2 on 2020-02-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyeong', models.IntegerField(verbose_name='평형')),
                ('product_type', models.CharField(max_length=100, verbose_name='제조사')),
                ('p_type', models.CharField(max_length=100, verbose_name='제품종류')),
                ('p_type2', models.CharField(blank=True, max_length=100, verbose_name='제품종류2')),
                ('grade', models.CharField(max_length=100, verbose_name='제품등급')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('image_url', models.URLField(blank=True, max_length=100, verbose_name='이미지')),
                ('image1', models.CharField(blank=True, max_length=100, verbose_name='이미지1')),
                ('image2', models.CharField(blank=True, max_length=100, verbose_name='이미지2')),
                ('image3', models.CharField(blank=True, max_length=100, verbose_name='이미지3')),
                ('p1', models.CharField(blank=True, max_length=100, verbose_name='p1')),
                ('p2', models.CharField(blank=True, max_length=100, verbose_name='p2')),
                ('p3', models.CharField(blank=True, max_length=100, verbose_name='p3')),
                ('p4', models.CharField(blank=True, max_length=100, verbose_name='p4')),
                ('p5', models.CharField(blank=True, max_length=100, verbose_name='p5')),
                ('p6', models.CharField(blank=True, max_length=100, verbose_name='p6')),
                ('p7', models.CharField(blank=True, max_length=100, verbose_name='p7')),
                ('i1', models.IntegerField(blank=True, verbose_name='i1')),
                ('i2', models.IntegerField(blank=True, verbose_name='i2')),
                ('i3', models.IntegerField(blank=True, verbose_name='i3')),
                ('i4', models.IntegerField(blank=True, verbose_name='i4')),
                ('i5', models.IntegerField(blank=True, verbose_name='i5')),
                ('i6', models.IntegerField(blank=True, verbose_name='i6')),
            ],
        ),
    ]
