# Generated by Django 2.2.2 on 2020-02-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='i1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='i2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='i3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='i4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='i5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='i6',
        ),
    ]
