# Generated by Django 2.2.2 on 2020-02-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200218_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='i1',
            field=models.IntegerField(blank=True, null=True, verbose_name='i1'),
        ),
        migrations.AddField(
            model_name='product',
            name='i2',
            field=models.IntegerField(blank=True, null=True, verbose_name='i2'),
        ),
        migrations.AddField(
            model_name='product',
            name='i3',
            field=models.IntegerField(blank=True, null=True, verbose_name='i3'),
        ),
        migrations.AddField(
            model_name='product',
            name='i4',
            field=models.IntegerField(blank=True, null=True, verbose_name='i4'),
        ),
        migrations.AddField(
            model_name='product',
            name='i5',
            field=models.IntegerField(blank=True, null=True, verbose_name='i5'),
        ),
        migrations.AddField(
            model_name='product',
            name='i6',
            field=models.IntegerField(blank=True, null=True, verbose_name='i6'),
        ),
    ]
