# Generated by Django 2.2.2 on 2020-02-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200218_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, verbose_name='종류')),
                ('service_type', models.CharField(max_length=100, verbose_name='서비스종류')),
                ('aircon_type', models.CharField(blank=True, max_length=100, verbose_name='에어컨종류')),
                ('company', models.CharField(max_length=100, verbose_name='제조사')),
                ('structure', models.CharField(max_length=100, verbose_name='배관형태')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('p1', models.CharField(blank=True, max_length=100, verbose_name='p1')),
                ('p2', models.CharField(blank=True, max_length=100, verbose_name='p2')),
                ('p3', models.CharField(blank=True, max_length=100, verbose_name='p3')),
                ('p4', models.CharField(blank=True, max_length=100, verbose_name='p4')),
                ('i1', models.IntegerField(blank=True, null=True, verbose_name='i1')),
                ('i2', models.IntegerField(blank=True, null=True, verbose_name='i2')),
                ('i3', models.IntegerField(blank=True, null=True, verbose_name='i3')),
            ],
        ),
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, verbose_name='종류')),
                ('pyeong', models.IntegerField(verbose_name='평형')),
                ('grade', models.CharField(max_length=100, verbose_name='사양')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('p1', models.CharField(blank=True, max_length=100, verbose_name='p1')),
                ('p2', models.CharField(blank=True, max_length=100, verbose_name='p2')),
                ('p3', models.CharField(blank=True, max_length=100, verbose_name='p3')),
                ('p4', models.CharField(blank=True, max_length=100, verbose_name='p4')),
                ('i1', models.IntegerField(blank=True, null=True, verbose_name='i1')),
                ('i2', models.IntegerField(blank=True, null=True, verbose_name='i2')),
                ('i3', models.IntegerField(blank=True, null=True, verbose_name='i3')),
            ],
        ),
        migrations.CreateModel(
            name='Onsugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100, verbose_name='종류')),
                ('capacity', models.IntegerField(verbose_name='용량')),
                ('fuel', models.CharField(max_length=100, verbose_name='사용연료')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('p1', models.CharField(blank=True, max_length=100, verbose_name='p1')),
                ('p2', models.CharField(blank=True, max_length=100, verbose_name='p2')),
                ('p3', models.CharField(blank=True, max_length=100, verbose_name='p3')),
                ('p4', models.CharField(blank=True, max_length=100, verbose_name='p4')),
                ('i1', models.IntegerField(blank=True, null=True, verbose_name='i1')),
                ('i2', models.IntegerField(blank=True, null=True, verbose_name='i2')),
                ('i3', models.IntegerField(blank=True, null=True, verbose_name='i3')),
            ],
        ),
    ]
