# Generated by Django 2.2.2 on 2020-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_consult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='reply',
            field=models.CharField(blank=True, max_length=400, verbose_name='reply'),
        ),
    ]
