# Generated by Django 2.2.2 on 2020-02-23 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200222_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='time',
            field=models.DateField(default=datetime.datetime.today, verbose_name='time'),
        ),
    ]
