# Generated by Django 2.2.2 on 2020-02-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200223_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='reply_check',
            field=models.CharField(blank=True, max_length=1, verbose_name='reply_check'),
        ),
    ]
