# Generated by Django 2.2.2 on 2020-02-23 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_consult_reply_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='reply_check',
        ),
        migrations.AddField(
            model_name='consult',
            name='title',
            field=models.CharField(default="a", max_length=15, verbose_name='title'),
            preserve_default=False,
        ),
    ]
