# Generated by Django 2.2.2 on 2020-02-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200223_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='title'),
        ),
    ]
