# Generated by Django 2.2.2 on 2020-02-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200223_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='title',
        ),
    ]
