# Generated by Django 2.2.2 on 2020-02-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_consult_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='content',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='i1',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='i2',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='i3',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='name',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='time',
        ),
    ]
