# Generated by Django 2.2.2 on 2020-02-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200223_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consult',
        ),
    ]
