# Generated by Django 2.2.2 on 2020-02-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200223_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consult',
        ),
    ]
