# Generated by Django 2.2.2 on 2020-02-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_consult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consult',
        ),
    ]
