# Generated by Django 2.2.2 on 2020-02-25 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_popup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Popup',
        ),
    ]
