# Generated by Django 2.2.2 on 2020-02-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_delete_popup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='popup')),
            ],
        ),
    ]
